steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetech'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetech'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]